---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  # Project description
  description: Project configurations for dev

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - '*'

  # Permit applications to deploy to namespaces in the same cluster
  destinations:
    - namespace: '*'
      server: '*'

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
