# https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: dev
  source:
    helm:
      values: |
        namespace: kube-system
        autoDiscovery:
          clusterName: nucleus-rogue-1
        awsRegion: us-west-2
        rbac:
          serviceAccount:
            create: false
            name: cluster-autoscaler
        extraArgs:
          v: 4
          logtostderr: true
          stderrthreshold: info
          balance-similar-node-groups: true
          skip-nodes-with-system-pods: false
          skip-nodes-with-local-storage: false
    chart: cluster-autoscaler
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.14.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
